# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @noRd
gehan_ns <- function(b, X, Y, d, W) {
    .Call('_paft_gehan_ns', PACKAGE = 'paft', b, X, Y, d, W)
}

#' @noRd
gehan_s <- function(b, X, y, d, w) {
    .Call('_paft_gehan_s', PACKAGE = 'paft', b, X, y, d, w)
}

#' @noRd
pgeeCpp <- function(X, y, weights, id, lambda, b0, pindex, corstr = "independence", maxit = 500L, eps = 1e-6, tol = 1e-3, SHEMonly = FALSE, penalty = "SCAD", olsb = 0L) {
    .Call('_paft_pgeeCpp', PACKAGE = 'paft', X, y, weights, id, lambda, b0, pindex, corstr, maxit, eps, tol, SHEMonly, penalty, olsb)
}

pgee <- function(y, X, b0, nt, pindex, w, penalty, corstr, lambda, eps, tol, maxit) {
    .Call('_paft_pgee', PACKAGE = 'paft', y, X, b0, nt, pindex, w, penalty, corstr, lambda, eps, tol, maxit)
}

gee <- function(y, X, b0, nt, w, corstr, tol, maxit) {
    .Call('_paft_gee', PACKAGE = 'paft', y, X, b0, nt, w, corstr, tol, maxit)
}

eResC <- function(Time, censor, wgt) {
    .Call('_paft_eResC', PACKAGE = 'paft', Time, censor, wgt)
}

aftgeeEst <- function(y, X, D, b0, nt, w, corstr, tol, maxit) {
    .Call('_paft_aftgeeEst', PACKAGE = 'paft', y, X, D, b0, nt, w, corstr, tol, maxit)
}

paftgeeEst <- function(y, X, D, b0, nt, pindex, w, penalty, corstr, lambda, eps, tol, maxit) {
    .Call('_paft_paftgeeEst', PACKAGE = 'paft', y, X, D, b0, nt, pindex, w, penalty, corstr, lambda, eps, tol, maxit)
}

paftgeeCV <- function(y, X, D, b0, nt, pindex, w, penalty, nCV, lambda, CVprop, eps, tol, maxit) {
    .Call('_paft_paftgeeCV', PACKAGE = 'paft', y, X, D, b0, nt, pindex, w, penalty, nCV, lambda, CVprop, eps, tol, maxit)
}

paftgeeBIC <- function(y, X, D, b0, nt, pindex, w, penalty, lambda, eps, tol, maxit) {
    .Call('_paft_paftgeeBIC', PACKAGE = 'paft', y, X, D, b0, nt, pindex, w, penalty, lambda, eps, tol, maxit)
}

paftgeeEst1 <- function(y, X, D, b0, nt, pindex, w, penalty, nCV, corstr, lambda, CVprop, rule, eps, tol, maxit) {
    .Call('_paft_paftgeeEst1', PACKAGE = 'paft', y, X, D, b0, nt, pindex, w, penalty, nCV, corstr, lambda, CVprop, rule, eps, tol, maxit)
}

